// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStation.proto

package ca.wise.weather.proto;

public final class CwfgmWeatherStationOuterClass {
  private CwfgmWeatherStationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_CwfgmWeatherStation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031cwfgmWeatherStation.proto\022\021WISE.Weathe" +
      "rProto\032\nmath.proto\032\017geography.proto\032\030cwf" +
      "gmWeatherStream.proto\032\036google/protobuf/w" +
      "rappers.proto\"\360\002\n\023CwfgmWeatherStation\022\017\n" +
      "\007version\030\001 \001(\005\022%\n\010location\030\002 \001(\0132\023.Geogr" +
      "aphy.GeoPoint\022\037\n\televation\030\003 \001(\0132\014.Math." +
      "Double\022.\n\nskipStream\030\004 \001(\0132\032.google.prot" +
      "obuf.BoolValue\0226\n\007streams\030\005 \003(\0132%.WISE.W" +
      "eatherProto.CwfgmWeatherStream\022\021\n\004name\030\006" +
      " \001(\tH\000\210\001\001\022\025\n\010comments\030\007 \001(\tH\001\210\001\001\022\022\n\005colo" +
      "r\030\010 \001(\rH\002\210\001\001\022\021\n\004size\030\t \001(\004H\003\210\001\001\022\023\n\006symbo" +
      "l\030\n \001(\004H\004\210\001\001B\007\n\005_nameB\013\n\t_commentsB\010\n\006_c" +
      "olorB\007\n\005_sizeB\t\n\007_symbolB-\n\025ca.wise.weat" +
      "her.protoP\001\252\002\021WISE.WeatherProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.hss.math.proto.Geography.getDescriptor(),
          ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_WeatherProto_CwfgmWeatherStation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor,
        new java.lang.String[] { "Version", "Location", "Elevation", "SkipStream", "Streams", "Name", "Comments", "Color", "Size", "Symbol", "Name", "Comments", "Color", "Size", "Symbol", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.hss.math.proto.Geography.getDescriptor();
    ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
