// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStream.proto

package ca.wise.weather.proto;

public final class CwfgmWeatherStreamOuterClass {
  private CwfgmWeatherStreamOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_CwfgmWeatherStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030cwfgmWeatherStream.proto\022\021WISE.Weather" +
      "Proto\032\023weatherStream.proto\032\036google/proto" +
      "buf/wrappers.proto\"\266\001\n\022CwfgmWeatherStrea" +
      "m\022\017\n\007version\030\001 \001(\005\022*\n\004name\030\002 \001(\0132\034.googl" +
      "e.protobuf.StringValue\022.\n\010comments\030\003 \001(\013" +
      "2\034.google.protobuf.StringValue\0223\n\tcondit" +
      "ion\030\004 \001(\0132 .WISE.WeatherProto.WeatherStr" +
      "eamB-\n\025ca.wise.weather.protoP\001\252\002\021WISE.We" +
      "atherProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.wise.weather.proto.WeatherStreamOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_WeatherProto_CwfgmWeatherStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor,
        new java.lang.String[] { "Version", "Name", "Comments", "Condition", });
    ca.wise.weather.proto.WeatherStreamOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
