// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStream.proto

package ca.wise.weather.proto;

/**
 * Protobuf type {@code WISE.WeatherProto.CwfgmWeatherStream}
 */
public final class CwfgmWeatherStream extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.WeatherProto.CwfgmWeatherStream)
    CwfgmWeatherStreamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmWeatherStream.newBuilder() to construct.
  private CwfgmWeatherStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmWeatherStream() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmWeatherStream();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmWeatherStream(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (comments_ != null) {
              subBuilder = comments_.toBuilder();
            }
            comments_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(comments_);
              comments_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            ca.wise.weather.proto.WeatherStream.Builder subBuilder = null;
            if (condition_ != null) {
              subBuilder = condition_.toBuilder();
            }
            condition_ = input.readMessage(ca.wise.weather.proto.WeatherStream.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(condition_);
              condition_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStream_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.weather.proto.CwfgmWeatherStream.class, ca.wise.weather.proto.CwfgmWeatherStream.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue name_;
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getName() {
    return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int COMMENTS_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue comments_;
  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   * @return Whether the comments field is set.
   */
  @java.lang.Override
  public boolean hasComments() {
    return comments_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   * @return The comments.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getComments() {
    return comments_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : comments_;
  }
  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getCommentsOrBuilder() {
    return getComments();
  }

  public static final int CONDITION_FIELD_NUMBER = 4;
  private ca.wise.weather.proto.WeatherStream condition_;
  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   * @return Whether the condition field is set.
   */
  @java.lang.Override
  public boolean hasCondition() {
    return condition_ != null;
  }
  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   * @return The condition.
   */
  @java.lang.Override
  public ca.wise.weather.proto.WeatherStream getCondition() {
    return condition_ == null ? ca.wise.weather.proto.WeatherStream.getDefaultInstance() : condition_;
  }
  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   */
  @java.lang.Override
  public ca.wise.weather.proto.WeatherStreamOrBuilder getConditionOrBuilder() {
    return getCondition();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (name_ != null) {
      output.writeMessage(2, getName());
    }
    if (comments_ != null) {
      output.writeMessage(3, getComments());
    }
    if (condition_ != null) {
      output.writeMessage(4, getCondition());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getName());
    }
    if (comments_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getComments());
    }
    if (condition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCondition());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.weather.proto.CwfgmWeatherStream)) {
      return super.equals(obj);
    }
    ca.wise.weather.proto.CwfgmWeatherStream other = (ca.wise.weather.proto.CwfgmWeatherStream) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasComments() != other.hasComments()) return false;
    if (hasComments()) {
      if (!getComments()
          .equals(other.getComments())) return false;
    }
    if (hasCondition() != other.hasCondition()) return false;
    if (hasCondition()) {
      if (!getCondition()
          .equals(other.getCondition())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    if (hasCondition()) {
      hash = (37 * hash) + CONDITION_FIELD_NUMBER;
      hash = (53 * hash) + getCondition().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.weather.proto.CwfgmWeatherStream prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.WeatherProto.CwfgmWeatherStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.WeatherProto.CwfgmWeatherStream)
      ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.weather.proto.CwfgmWeatherStream.class, ca.wise.weather.proto.CwfgmWeatherStream.Builder.class);
    }

    // Construct using ca.wise.weather.proto.CwfgmWeatherStream.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (commentsBuilder_ == null) {
        comments_ = null;
      } else {
        comments_ = null;
        commentsBuilder_ = null;
      }
      if (conditionBuilder_ == null) {
        condition_ = null;
      } else {
        condition_ = null;
        conditionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.weather.proto.CwfgmWeatherStreamOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStream_descriptor;
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStream getDefaultInstanceForType() {
      return ca.wise.weather.proto.CwfgmWeatherStream.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStream build() {
      ca.wise.weather.proto.CwfgmWeatherStream result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStream buildPartial() {
      ca.wise.weather.proto.CwfgmWeatherStream result = new ca.wise.weather.proto.CwfgmWeatherStream(this);
      result.version_ = version_;
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (commentsBuilder_ == null) {
        result.comments_ = comments_;
      } else {
        result.comments_ = commentsBuilder_.build();
      }
      if (conditionBuilder_ == null) {
        result.condition_ = condition_;
      } else {
        result.condition_ = conditionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.weather.proto.CwfgmWeatherStream) {
        return mergeFrom((ca.wise.weather.proto.CwfgmWeatherStream)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.weather.proto.CwfgmWeatherStream other) {
      if (other == ca.wise.weather.proto.CwfgmWeatherStream.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasComments()) {
        mergeComments(other.getComments());
      }
      if (other.hasCondition()) {
        mergeCondition(other.getCondition());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.weather.proto.CwfgmWeatherStream parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.weather.proto.CwfgmWeatherStream) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue name_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     * @return The name.
     */
    public com.google.protobuf.StringValue getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder mergeName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.StringValue comments_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> commentsBuilder_;
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     * @return Whether the comments field is set.
     */
    public boolean hasComments() {
      return commentsBuilder_ != null || comments_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     * @return The comments.
     */
    public com.google.protobuf.StringValue getComments() {
      if (commentsBuilder_ == null) {
        return comments_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : comments_;
      } else {
        return commentsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public Builder setComments(com.google.protobuf.StringValue value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        comments_ = value;
        onChanged();
      } else {
        commentsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public Builder setComments(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        comments_ = builderForValue.build();
        onChanged();
      } else {
        commentsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public Builder mergeComments(com.google.protobuf.StringValue value) {
      if (commentsBuilder_ == null) {
        if (comments_ != null) {
          comments_ =
            com.google.protobuf.StringValue.newBuilder(comments_).mergeFrom(value).buildPartial();
        } else {
          comments_ = value;
        }
        onChanged();
      } else {
        commentsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public Builder clearComments() {
      if (commentsBuilder_ == null) {
        comments_ = null;
        onChanged();
      } else {
        comments_ = null;
        commentsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getCommentsBuilder() {
      
      onChanged();
      return getCommentsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getCommentsOrBuilder() {
      if (commentsBuilder_ != null) {
        return commentsBuilder_.getMessageOrBuilder();
      } else {
        return comments_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : comments_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue comments = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getCommentsFieldBuilder() {
      if (commentsBuilder_ == null) {
        commentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getComments(),
                getParentForChildren(),
                isClean());
        comments_ = null;
      }
      return commentsBuilder_;
    }

    private ca.wise.weather.proto.WeatherStream condition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.weather.proto.WeatherStream, ca.wise.weather.proto.WeatherStream.Builder, ca.wise.weather.proto.WeatherStreamOrBuilder> conditionBuilder_;
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     * @return Whether the condition field is set.
     */
    public boolean hasCondition() {
      return conditionBuilder_ != null || condition_ != null;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     * @return The condition.
     */
    public ca.wise.weather.proto.WeatherStream getCondition() {
      if (conditionBuilder_ == null) {
        return condition_ == null ? ca.wise.weather.proto.WeatherStream.getDefaultInstance() : condition_;
      } else {
        return conditionBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public Builder setCondition(ca.wise.weather.proto.WeatherStream value) {
      if (conditionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        condition_ = value;
        onChanged();
      } else {
        conditionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public Builder setCondition(
        ca.wise.weather.proto.WeatherStream.Builder builderForValue) {
      if (conditionBuilder_ == null) {
        condition_ = builderForValue.build();
        onChanged();
      } else {
        conditionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public Builder mergeCondition(ca.wise.weather.proto.WeatherStream value) {
      if (conditionBuilder_ == null) {
        if (condition_ != null) {
          condition_ =
            ca.wise.weather.proto.WeatherStream.newBuilder(condition_).mergeFrom(value).buildPartial();
        } else {
          condition_ = value;
        }
        onChanged();
      } else {
        conditionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public Builder clearCondition() {
      if (conditionBuilder_ == null) {
        condition_ = null;
        onChanged();
      } else {
        condition_ = null;
        conditionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public ca.wise.weather.proto.WeatherStream.Builder getConditionBuilder() {
      
      onChanged();
      return getConditionFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    public ca.wise.weather.proto.WeatherStreamOrBuilder getConditionOrBuilder() {
      if (conditionBuilder_ != null) {
        return conditionBuilder_.getMessageOrBuilder();
      } else {
        return condition_ == null ?
            ca.wise.weather.proto.WeatherStream.getDefaultInstance() : condition_;
      }
    }
    /**
     * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.weather.proto.WeatherStream, ca.wise.weather.proto.WeatherStream.Builder, ca.wise.weather.proto.WeatherStreamOrBuilder> 
        getConditionFieldBuilder() {
      if (conditionBuilder_ == null) {
        conditionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.weather.proto.WeatherStream, ca.wise.weather.proto.WeatherStream.Builder, ca.wise.weather.proto.WeatherStreamOrBuilder>(
                getCondition(),
                getParentForChildren(),
                isClean());
        condition_ = null;
      }
      return conditionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.WeatherProto.CwfgmWeatherStream)
  }

  // @@protoc_insertion_point(class_scope:WISE.WeatherProto.CwfgmWeatherStream)
  private static final ca.wise.weather.proto.CwfgmWeatherStream DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.weather.proto.CwfgmWeatherStream();
  }

  public static ca.wise.weather.proto.CwfgmWeatherStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmWeatherStream>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmWeatherStream>() {
    @java.lang.Override
    public CwfgmWeatherStream parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmWeatherStream(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmWeatherStream> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmWeatherStream> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.weather.proto.CwfgmWeatherStream getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

