// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStation.proto

package ca.wise.weather.proto;

public interface CwfgmWeatherStationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.CwfgmWeatherStation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   * @return The location.
   */
  ca.hss.math.proto.GeoPoint getLocation();
  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   */
  ca.hss.math.proto.GeoPointOrBuilder getLocationOrBuilder();

  /**
   * <code>.Math.Double elevation = 3;</code>
   * @return Whether the elevation field is set.
   */
  boolean hasElevation();
  /**
   * <code>.Math.Double elevation = 3;</code>
   * @return The elevation.
   */
  ca.hss.math.proto.Double getElevation();
  /**
   * <code>.Math.Double elevation = 3;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getElevationOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   * @return Whether the skipStream field is set.
   */
  boolean hasSkipStream();
  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   * @return The skipStream.
   */
  com.google.protobuf.BoolValue getSkipStream();
  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getSkipStreamOrBuilder();

  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  java.util.List<ca.wise.weather.proto.CwfgmWeatherStream> 
      getStreamsList();
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  ca.wise.weather.proto.CwfgmWeatherStream getStreams(int index);
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  int getStreamsCount();
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  java.util.List<? extends ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder> 
      getStreamsOrBuilderList();
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder getStreamsOrBuilder(
      int index);

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 7;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 7;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 7;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 8;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>uint32 color = 8;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint64 size = 9;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>uint64 size = 9;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>uint64 symbol = 10;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>uint64 symbol = 10;</code>
   * @return The symbol.
   */
  long getSymbol();
}
