// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStation.proto

package ca.wise.weather.proto;

/**
 * Protobuf type {@code WISE.WeatherProto.CwfgmWeatherStation}
 */
public final class CwfgmWeatherStation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.WeatherProto.CwfgmWeatherStation)
    CwfgmWeatherStationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CwfgmWeatherStation.newBuilder() to construct.
  private CwfgmWeatherStation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CwfgmWeatherStation() {
    streams_ = java.util.Collections.emptyList();
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CwfgmWeatherStation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CwfgmWeatherStation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.hss.math.proto.GeoPoint.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(ca.hss.math.proto.GeoPoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (elevation_ != null) {
              subBuilder = elevation_.toBuilder();
            }
            elevation_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elevation_);
              elevation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (skipStream_ != null) {
              subBuilder = skipStream_.toBuilder();
            }
            skipStream_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(skipStream_);
              skipStream_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              streams_ = new java.util.ArrayList<ca.wise.weather.proto.CwfgmWeatherStream>();
              mutable_bitField0_ |= 0x00000001;
            }
            streams_.add(
                input.readMessage(ca.wise.weather.proto.CwfgmWeatherStream.parser(), extensionRegistry));
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            name_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            comments_ = s;
            break;
          }
          case 64: {
            bitField0_ |= 0x00000004;
            color_ = input.readUInt32();
            break;
          }
          case 72: {
            bitField0_ |= 0x00000008;
            size_ = input.readUInt64();
            break;
          }
          case 80: {
            bitField0_ |= 0x00000010;
            symbol_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        streams_ = java.util.Collections.unmodifiableList(streams_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.weather.proto.CwfgmWeatherStationOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.weather.proto.CwfgmWeatherStationOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.weather.proto.CwfgmWeatherStation.class, ca.wise.weather.proto.CwfgmWeatherStation.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private ca.hss.math.proto.GeoPoint location_;
  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   * @return The location.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoint getLocation() {
    return location_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : location_;
  }
  /**
   * <code>.Geography.GeoPoint location = 2;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPointOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int ELEVATION_FIELD_NUMBER = 3;
  private ca.hss.math.proto.Double elevation_;
  /**
   * <code>.Math.Double elevation = 3;</code>
   * @return Whether the elevation field is set.
   */
  @java.lang.Override
  public boolean hasElevation() {
    return elevation_ != null;
  }
  /**
   * <code>.Math.Double elevation = 3;</code>
   * @return The elevation.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getElevation() {
    return elevation_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : elevation_;
  }
  /**
   * <code>.Math.Double elevation = 3;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getElevationOrBuilder() {
    return getElevation();
  }

  public static final int SKIPSTREAM_FIELD_NUMBER = 4;
  private com.google.protobuf.BoolValue skipStream_;
  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   * @return Whether the skipStream field is set.
   */
  @java.lang.Override
  public boolean hasSkipStream() {
    return skipStream_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   * @return The skipStream.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getSkipStream() {
    return skipStream_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : skipStream_;
  }
  /**
   * <code>.google.protobuf.BoolValue skipStream = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getSkipStreamOrBuilder() {
    return getSkipStream();
  }

  public static final int STREAMS_FIELD_NUMBER = 5;
  private java.util.List<ca.wise.weather.proto.CwfgmWeatherStream> streams_;
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.weather.proto.CwfgmWeatherStream> getStreamsList() {
    return streams_;
  }
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder> 
      getStreamsOrBuilderList() {
    return streams_;
  }
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  @java.lang.Override
  public int getStreamsCount() {
    return streams_.size();
  }
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  @java.lang.Override
  public ca.wise.weather.proto.CwfgmWeatherStream getStreams(int index) {
    return streams_.get(index);
  }
  /**
   * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
   */
  @java.lang.Override
  public ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder getStreamsOrBuilder(
      int index) {
    return streams_.get(index);
  }

  public static final int NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 7;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 7;</code>
   * @return Whether the comments field is set.
   */
  @java.lang.Override
  public boolean hasComments() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string comments = 7;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 7;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 8;
  private int color_;
  /**
   * <code>uint32 color = 8;</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>uint32 color = 8;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int SIZE_FIELD_NUMBER = 9;
  private long size_;
  /**
   * <code>uint64 size = 9;</code>
   * @return Whether the size field is set.
   */
  @java.lang.Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>uint64 size = 9;</code>
   * @return The size.
   */
  @java.lang.Override
  public long getSize() {
    return size_;
  }

  public static final int SYMBOL_FIELD_NUMBER = 10;
  private long symbol_;
  /**
   * <code>uint64 symbol = 10;</code>
   * @return Whether the symbol field is set.
   */
  @java.lang.Override
  public boolean hasSymbol() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>uint64 symbol = 10;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public long getSymbol() {
    return symbol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (location_ != null) {
      output.writeMessage(2, getLocation());
    }
    if (elevation_ != null) {
      output.writeMessage(3, getElevation());
    }
    if (skipStream_ != null) {
      output.writeMessage(4, getSkipStream());
    }
    for (int i = 0; i < streams_.size(); i++) {
      output.writeMessage(5, streams_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(8, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(9, size_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt64(10, symbol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocation());
    }
    if (elevation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getElevation());
    }
    if (skipStream_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSkipStream());
    }
    for (int i = 0; i < streams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, streams_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, comments_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, color_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, size_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, symbol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.weather.proto.CwfgmWeatherStation)) {
      return super.equals(obj);
    }
    ca.wise.weather.proto.CwfgmWeatherStation other = (ca.wise.weather.proto.CwfgmWeatherStation) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (hasElevation() != other.hasElevation()) return false;
    if (hasElevation()) {
      if (!getElevation()
          .equals(other.getElevation())) return false;
    }
    if (hasSkipStream() != other.hasSkipStream()) return false;
    if (hasSkipStream()) {
      if (!getSkipStream()
          .equals(other.getSkipStream())) return false;
    }
    if (!getStreamsList()
        .equals(other.getStreamsList())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasComments() != other.hasComments()) return false;
    if (hasComments()) {
      if (!getComments()
          .equals(other.getComments())) return false;
    }
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (getColor()
          != other.getColor()) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (getSize()
          != other.getSize()) return false;
    }
    if (hasSymbol() != other.hasSymbol()) return false;
    if (hasSymbol()) {
      if (getSymbol()
          != other.getSymbol()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (hasElevation()) {
      hash = (37 * hash) + ELEVATION_FIELD_NUMBER;
      hash = (53 * hash) + getElevation().hashCode();
    }
    if (hasSkipStream()) {
      hash = (37 * hash) + SKIPSTREAM_FIELD_NUMBER;
      hash = (53 * hash) + getSkipStream().hashCode();
    }
    if (getStreamsCount() > 0) {
      hash = (37 * hash) + STREAMS_FIELD_NUMBER;
      hash = (53 * hash) + getStreamsList().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasComments()) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComments().hashCode();
    }
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
    }
    if (hasSymbol()) {
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSymbol());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.CwfgmWeatherStation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.weather.proto.CwfgmWeatherStation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.WeatherProto.CwfgmWeatherStation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.WeatherProto.CwfgmWeatherStation)
      ca.wise.weather.proto.CwfgmWeatherStationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.weather.proto.CwfgmWeatherStationOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.weather.proto.CwfgmWeatherStationOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.weather.proto.CwfgmWeatherStation.class, ca.wise.weather.proto.CwfgmWeatherStation.Builder.class);
    }

    // Construct using ca.wise.weather.proto.CwfgmWeatherStation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStreamsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      if (elevationBuilder_ == null) {
        elevation_ = null;
      } else {
        elevation_ = null;
        elevationBuilder_ = null;
      }
      if (skipStreamBuilder_ == null) {
        skipStream_ = null;
      } else {
        skipStream_ = null;
        skipStreamBuilder_ = null;
      }
      if (streamsBuilder_ == null) {
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        streamsBuilder_.clear();
      }
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      comments_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      color_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      size_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      symbol_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.weather.proto.CwfgmWeatherStationOuterClass.internal_static_WISE_WeatherProto_CwfgmWeatherStation_descriptor;
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStation getDefaultInstanceForType() {
      return ca.wise.weather.proto.CwfgmWeatherStation.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStation build() {
      ca.wise.weather.proto.CwfgmWeatherStation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.weather.proto.CwfgmWeatherStation buildPartial() {
      ca.wise.weather.proto.CwfgmWeatherStation result = new ca.wise.weather.proto.CwfgmWeatherStation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      if (elevationBuilder_ == null) {
        result.elevation_ = elevation_;
      } else {
        result.elevation_ = elevationBuilder_.build();
      }
      if (skipStreamBuilder_ == null) {
        result.skipStream_ = skipStream_;
      } else {
        result.skipStream_ = skipStreamBuilder_.build();
      }
      if (streamsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          streams_ = java.util.Collections.unmodifiableList(streams_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.streams_ = streams_;
      } else {
        result.streams_ = streamsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.comments_ = comments_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.color_ = color_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.size_ = size_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.symbol_ = symbol_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.weather.proto.CwfgmWeatherStation) {
        return mergeFrom((ca.wise.weather.proto.CwfgmWeatherStation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.weather.proto.CwfgmWeatherStation other) {
      if (other == ca.wise.weather.proto.CwfgmWeatherStation.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.hasElevation()) {
        mergeElevation(other.getElevation());
      }
      if (other.hasSkipStream()) {
        mergeSkipStream(other.getSkipStream());
      }
      if (streamsBuilder_ == null) {
        if (!other.streams_.isEmpty()) {
          if (streams_.isEmpty()) {
            streams_ = other.streams_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStreamsIsMutable();
            streams_.addAll(other.streams_);
          }
          onChanged();
        }
      } else {
        if (!other.streams_.isEmpty()) {
          if (streamsBuilder_.isEmpty()) {
            streamsBuilder_.dispose();
            streamsBuilder_ = null;
            streams_ = other.streams_;
            bitField0_ = (bitField0_ & ~0x00000001);
            streamsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStreamsFieldBuilder() : null;
          } else {
            streamsBuilder_.addAllMessages(other.streams_);
          }
        }
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasComments()) {
        bitField0_ |= 0x00000004;
        comments_ = other.comments_;
        onChanged();
      }
      if (other.hasColor()) {
        setColor(other.getColor());
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      if (other.hasSymbol()) {
        setSymbol(other.getSymbol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.weather.proto.CwfgmWeatherStation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.weather.proto.CwfgmWeatherStation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private ca.hss.math.proto.GeoPoint location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> locationBuilder_;
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     * @return The location.
     */
    public ca.hss.math.proto.GeoPoint getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? ca.hss.math.proto.GeoPoint.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public Builder setLocation(ca.hss.math.proto.GeoPoint value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public Builder setLocation(
        ca.hss.math.proto.GeoPoint.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public Builder mergeLocation(ca.hss.math.proto.GeoPoint value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            ca.hss.math.proto.GeoPoint.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public ca.hss.math.proto.GeoPoint.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    public ca.hss.math.proto.GeoPointOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            ca.hss.math.proto.GeoPoint.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.Geography.GeoPoint location = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoint, ca.hss.math.proto.GeoPoint.Builder, ca.hss.math.proto.GeoPointOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private ca.hss.math.proto.Double elevation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> elevationBuilder_;
    /**
     * <code>.Math.Double elevation = 3;</code>
     * @return Whether the elevation field is set.
     */
    public boolean hasElevation() {
      return elevationBuilder_ != null || elevation_ != null;
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     * @return The elevation.
     */
    public ca.hss.math.proto.Double getElevation() {
      if (elevationBuilder_ == null) {
        return elevation_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : elevation_;
      } else {
        return elevationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public Builder setElevation(ca.hss.math.proto.Double value) {
      if (elevationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elevation_ = value;
        onChanged();
      } else {
        elevationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public Builder setElevation(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (elevationBuilder_ == null) {
        elevation_ = builderForValue.build();
        onChanged();
      } else {
        elevationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public Builder mergeElevation(ca.hss.math.proto.Double value) {
      if (elevationBuilder_ == null) {
        if (elevation_ != null) {
          elevation_ =
            ca.hss.math.proto.Double.newBuilder(elevation_).mergeFrom(value).buildPartial();
        } else {
          elevation_ = value;
        }
        onChanged();
      } else {
        elevationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public Builder clearElevation() {
      if (elevationBuilder_ == null) {
        elevation_ = null;
        onChanged();
      } else {
        elevation_ = null;
        elevationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public ca.hss.math.proto.Double.Builder getElevationBuilder() {
      
      onChanged();
      return getElevationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getElevationOrBuilder() {
      if (elevationBuilder_ != null) {
        return elevationBuilder_.getMessageOrBuilder();
      } else {
        return elevation_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : elevation_;
      }
    }
    /**
     * <code>.Math.Double elevation = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getElevationFieldBuilder() {
      if (elevationBuilder_ == null) {
        elevationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getElevation(),
                getParentForChildren(),
                isClean());
        elevation_ = null;
      }
      return elevationBuilder_;
    }

    private com.google.protobuf.BoolValue skipStream_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> skipStreamBuilder_;
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     * @return Whether the skipStream field is set.
     */
    public boolean hasSkipStream() {
      return skipStreamBuilder_ != null || skipStream_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     * @return The skipStream.
     */
    public com.google.protobuf.BoolValue getSkipStream() {
      if (skipStreamBuilder_ == null) {
        return skipStream_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : skipStream_;
      } else {
        return skipStreamBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public Builder setSkipStream(com.google.protobuf.BoolValue value) {
      if (skipStreamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        skipStream_ = value;
        onChanged();
      } else {
        skipStreamBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public Builder setSkipStream(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (skipStreamBuilder_ == null) {
        skipStream_ = builderForValue.build();
        onChanged();
      } else {
        skipStreamBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public Builder mergeSkipStream(com.google.protobuf.BoolValue value) {
      if (skipStreamBuilder_ == null) {
        if (skipStream_ != null) {
          skipStream_ =
            com.google.protobuf.BoolValue.newBuilder(skipStream_).mergeFrom(value).buildPartial();
        } else {
          skipStream_ = value;
        }
        onChanged();
      } else {
        skipStreamBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public Builder clearSkipStream() {
      if (skipStreamBuilder_ == null) {
        skipStream_ = null;
        onChanged();
      } else {
        skipStream_ = null;
        skipStreamBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public com.google.protobuf.BoolValue.Builder getSkipStreamBuilder() {
      
      onChanged();
      return getSkipStreamFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getSkipStreamOrBuilder() {
      if (skipStreamBuilder_ != null) {
        return skipStreamBuilder_.getMessageOrBuilder();
      } else {
        return skipStream_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : skipStream_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue skipStream = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getSkipStreamFieldBuilder() {
      if (skipStreamBuilder_ == null) {
        skipStreamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getSkipStream(),
                getParentForChildren(),
                isClean());
        skipStream_ = null;
      }
      return skipStreamBuilder_;
    }

    private java.util.List<ca.wise.weather.proto.CwfgmWeatherStream> streams_ =
      java.util.Collections.emptyList();
    private void ensureStreamsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        streams_ = new java.util.ArrayList<ca.wise.weather.proto.CwfgmWeatherStream>(streams_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.weather.proto.CwfgmWeatherStream, ca.wise.weather.proto.CwfgmWeatherStream.Builder, ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder> streamsBuilder_;

    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public java.util.List<ca.wise.weather.proto.CwfgmWeatherStream> getStreamsList() {
      if (streamsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(streams_);
      } else {
        return streamsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public int getStreamsCount() {
      if (streamsBuilder_ == null) {
        return streams_.size();
      } else {
        return streamsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public ca.wise.weather.proto.CwfgmWeatherStream getStreams(int index) {
      if (streamsBuilder_ == null) {
        return streams_.get(index);
      } else {
        return streamsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder setStreams(
        int index, ca.wise.weather.proto.CwfgmWeatherStream value) {
      if (streamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamsIsMutable();
        streams_.set(index, value);
        onChanged();
      } else {
        streamsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder setStreams(
        int index, ca.wise.weather.proto.CwfgmWeatherStream.Builder builderForValue) {
      if (streamsBuilder_ == null) {
        ensureStreamsIsMutable();
        streams_.set(index, builderForValue.build());
        onChanged();
      } else {
        streamsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder addStreams(ca.wise.weather.proto.CwfgmWeatherStream value) {
      if (streamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamsIsMutable();
        streams_.add(value);
        onChanged();
      } else {
        streamsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder addStreams(
        int index, ca.wise.weather.proto.CwfgmWeatherStream value) {
      if (streamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamsIsMutable();
        streams_.add(index, value);
        onChanged();
      } else {
        streamsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder addStreams(
        ca.wise.weather.proto.CwfgmWeatherStream.Builder builderForValue) {
      if (streamsBuilder_ == null) {
        ensureStreamsIsMutable();
        streams_.add(builderForValue.build());
        onChanged();
      } else {
        streamsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder addStreams(
        int index, ca.wise.weather.proto.CwfgmWeatherStream.Builder builderForValue) {
      if (streamsBuilder_ == null) {
        ensureStreamsIsMutable();
        streams_.add(index, builderForValue.build());
        onChanged();
      } else {
        streamsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder addAllStreams(
        java.lang.Iterable<? extends ca.wise.weather.proto.CwfgmWeatherStream> values) {
      if (streamsBuilder_ == null) {
        ensureStreamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, streams_);
        onChanged();
      } else {
        streamsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder clearStreams() {
      if (streamsBuilder_ == null) {
        streams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        streamsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public Builder removeStreams(int index) {
      if (streamsBuilder_ == null) {
        ensureStreamsIsMutable();
        streams_.remove(index);
        onChanged();
      } else {
        streamsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public ca.wise.weather.proto.CwfgmWeatherStream.Builder getStreamsBuilder(
        int index) {
      return getStreamsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder getStreamsOrBuilder(
        int index) {
      if (streamsBuilder_ == null) {
        return streams_.get(index);  } else {
        return streamsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public java.util.List<? extends ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder> 
         getStreamsOrBuilderList() {
      if (streamsBuilder_ != null) {
        return streamsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(streams_);
      }
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public ca.wise.weather.proto.CwfgmWeatherStream.Builder addStreamsBuilder() {
      return getStreamsFieldBuilder().addBuilder(
          ca.wise.weather.proto.CwfgmWeatherStream.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public ca.wise.weather.proto.CwfgmWeatherStream.Builder addStreamsBuilder(
        int index) {
      return getStreamsFieldBuilder().addBuilder(
          index, ca.wise.weather.proto.CwfgmWeatherStream.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.WeatherProto.CwfgmWeatherStream streams = 5;</code>
     */
    public java.util.List<ca.wise.weather.proto.CwfgmWeatherStream.Builder> 
         getStreamsBuilderList() {
      return getStreamsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.weather.proto.CwfgmWeatherStream, ca.wise.weather.proto.CwfgmWeatherStream.Builder, ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder> 
        getStreamsFieldBuilder() {
      if (streamsBuilder_ == null) {
        streamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.weather.proto.CwfgmWeatherStream, ca.wise.weather.proto.CwfgmWeatherStream.Builder, ca.wise.weather.proto.CwfgmWeatherStreamOrBuilder>(
                streams_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        streams_ = null;
      }
      return streamsBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * not really optional but need to be able to suppress it in the old file format
     * </pre>
     *
     * <code>string name = 6;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 7;</code>
     * @return Whether the comments field is set.
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>string comments = 7;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 7;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 7;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      bitField0_ = (bitField0_ & ~0x00000004);
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 7;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      comments_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>uint32 color = 8;</code>
     * @return Whether the color field is set.
     */
    @java.lang.Override
    public boolean hasColor() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>uint32 color = 8;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <code>uint32 color = 8;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      bitField0_ |= 0x00000008;
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 color = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000008);
      color_ = 0;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <code>uint64 size = 9;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>uint64 size = 9;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }
    /**
     * <code>uint64 size = 9;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {
      bitField0_ |= 0x00000010;
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 size = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      size_ = 0L;
      onChanged();
      return this;
    }

    private long symbol_ ;
    /**
     * <code>uint64 symbol = 10;</code>
     * @return Whether the symbol field is set.
     */
    @java.lang.Override
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>uint64 symbol = 10;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public long getSymbol() {
      return symbol_;
    }
    /**
     * <code>uint64 symbol = 10;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(long value) {
      bitField0_ |= 0x00000020;
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 symbol = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      bitField0_ = (bitField0_ & ~0x00000020);
      symbol_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.WeatherProto.CwfgmWeatherStation)
  }

  // @@protoc_insertion_point(class_scope:WISE.WeatherProto.CwfgmWeatherStation)
  private static final ca.wise.weather.proto.CwfgmWeatherStation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.weather.proto.CwfgmWeatherStation();
  }

  public static ca.wise.weather.proto.CwfgmWeatherStation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CwfgmWeatherStation>
      PARSER = new com.google.protobuf.AbstractParser<CwfgmWeatherStation>() {
    @java.lang.Override
    public CwfgmWeatherStation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CwfgmWeatherStation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CwfgmWeatherStation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CwfgmWeatherStation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.weather.proto.CwfgmWeatherStation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

