// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cwfgmWeatherStream.proto

package ca.wise.weather.proto;

public interface CwfgmWeatherStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.CwfgmWeatherStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   * @return The name.
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   * @return The comments.
   */
  com.google.protobuf.StringValue getComments();
  /**
   * <code>.google.protobuf.StringValue comments = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCommentsOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   * @return Whether the condition field is set.
   */
  boolean hasCondition();
  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   * @return The condition.
   */
  ca.wise.weather.proto.WeatherStream getCondition();
  /**
   * <code>.WISE.WeatherProto.WeatherStream condition = 4;</code>
   */
  ca.wise.weather.proto.WeatherStreamOrBuilder getConditionOrBuilder();
}
