// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dailyConditions.proto

package ca.wise.weather.proto;

public final class DailyConditionsOuterClass {
  private DailyConditionsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyFwi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyFwi_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyConditions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyConditions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyConditions_DayWeather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyConditions_DayWeather_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyConditions_DayHourWeather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyConditions_DayHourWeather_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyConditions_HourWeather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyConditions_HourWeather_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_DailyConditions_SpecHour_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_DailyConditions_SpecHour_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025dailyConditions.proto\022\021WISE.WeatherPro" +
      "to\032\nmath.proto\032\036google/protobuf/wrappers" +
      ".proto\"\275\001\n\010DailyFwi\022\017\n\007version\030\001 \001(\005\022\032\n\004" +
      "ffmc\030\002 \001(\0132\014.Math.Double\022\031\n\003isi\030\003 \001(\0132\014." +
      "Math.Double\022\031\n\003fwi\030\004 \001(\0132\014.Math.Double\022\031" +
      "\n\003dmc\030\005 \001(\0132\014.Math.Double\022\030\n\002dc\030\006 \001(\0132\014." +
      "Math.Double\022\031\n\003bui\030\007 \001(\0132\014.Math.Double\"\213" +
      "\010\n\017DailyConditions\022\017\n\007version\030\001 \001(\005\022(\n\003f" +
      "wi\030\002 \001(\0132\033.WISE.WeatherProto.DailyFwi\022,\n" +
      "\010fromFile\030\003 \001(\0132\032.google.protobuf.BoolVa" +
      "lue\022C\n\ndayWeather\030\004 \001(\0132-.WISE.WeatherPr" +
      "oto.DailyConditions.DayWeatherH\000\022H\n\013hour" +
      "Weather\030\005 \001(\01321.WISE.WeatherProto.DailyC" +
      "onditions.DayHourWeatherH\000\022=\n\010specHour\030\006" +
      " \003(\0132+.WISE.WeatherProto.DailyConditions" +
      ".SpecHour\0220\n\014fromEnsemble\030\007 \001(\0132\032.google" +
      ".protobuf.BoolValue\022.\n\nisModified\030\010 \001(\0132" +
      "\032.google.protobuf.BoolValue\032\326\001\n\nDayWeath" +
      "er\022\035\n\007maxTemp\030\001 \001(\0132\014.Math.Double\022\033\n\005max" +
      "Ws\030\002 \001(\0132\014.Math.Double\022\035\n\007minTemp\030\003 \001(\0132" +
      "\014.Math.Double\022\033\n\005minWs\030\004 \001(\0132\014.Math.Doub" +
      "le\022\034\n\006precip\030\005 \001(\0132\014.Math.Double\022\030\n\002rh\030\006" +
      " \001(\0132\014.Math.Double\022\030\n\002wd\030\007 \001(\0132\014.Math.Do" +
      "uble\032O\n\016DayHourWeather\022=\n\005hours\030\001 \003(\0132.." +
      "WISE.WeatherProto.DailyConditions.HourWe" +
      "ather\032\313\001\n\013HourWeather\022\036\n\010dewPoint\030\001 \001(\0132" +
      "\014.Math.Double\022\024\n\014interpolated\030\002 \001(\010\022\034\n\006p" +
      "recip\030\003 \001(\0132\014.Math.Double\022\030\n\002rh\030\004 \001(\0132\014." +
      "Math.Double\022\032\n\004temp\030\005 \001(\0132\014.Math.Double\022" +
      "\030\n\002wd\030\006 \001(\0132\014.Math.Double\022\030\n\002ws\030\007 \001(\0132\014." +
      "Math.Double\032\\\n\010SpecHour\022\032\n\004ffmc\030\001 \001(\0132\014." +
      "Math.Double\022\031\n\003fwi\030\002 \001(\0132\014.Math.Double\022\031" +
      "\n\003isi\030\003 \001(\0132\014.Math.DoubleB\t\n\007weatherB-\n\025" +
      "ca.wise.weather.protoP\001\252\002\021WISE.WeatherPr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_WeatherProto_DailyFwi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_WeatherProto_DailyFwi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyFwi_descriptor,
        new java.lang.String[] { "Version", "Ffmc", "Isi", "Fwi", "Dmc", "Dc", "Bui", });
    internal_static_WISE_WeatherProto_DailyConditions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_WeatherProto_DailyConditions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyConditions_descriptor,
        new java.lang.String[] { "Version", "Fwi", "FromFile", "DayWeather", "HourWeather", "SpecHour", "FromEnsemble", "IsModified", "Weather", });
    internal_static_WISE_WeatherProto_DailyConditions_DayWeather_descriptor =
      internal_static_WISE_WeatherProto_DailyConditions_descriptor.getNestedTypes().get(0);
    internal_static_WISE_WeatherProto_DailyConditions_DayWeather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyConditions_DayWeather_descriptor,
        new java.lang.String[] { "MaxTemp", "MaxWs", "MinTemp", "MinWs", "Precip", "Rh", "Wd", });
    internal_static_WISE_WeatherProto_DailyConditions_DayHourWeather_descriptor =
      internal_static_WISE_WeatherProto_DailyConditions_descriptor.getNestedTypes().get(1);
    internal_static_WISE_WeatherProto_DailyConditions_DayHourWeather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyConditions_DayHourWeather_descriptor,
        new java.lang.String[] { "Hours", });
    internal_static_WISE_WeatherProto_DailyConditions_HourWeather_descriptor =
      internal_static_WISE_WeatherProto_DailyConditions_descriptor.getNestedTypes().get(2);
    internal_static_WISE_WeatherProto_DailyConditions_HourWeather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyConditions_HourWeather_descriptor,
        new java.lang.String[] { "DewPoint", "Interpolated", "Precip", "Rh", "Temp", "Wd", "Ws", });
    internal_static_WISE_WeatherProto_DailyConditions_SpecHour_descriptor =
      internal_static_WISE_WeatherProto_DailyConditions_descriptor.getNestedTypes().get(3);
    internal_static_WISE_WeatherProto_DailyConditions_SpecHour_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_DailyConditions_SpecHour_descriptor,
        new java.lang.String[] { "Ffmc", "Fwi", "Isi", });
    ca.hss.math.proto.Math.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
