// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dailyConditions.proto

package ca.wise.weather.proto;

public interface DailyFwiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.DailyFwi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.Math.Double ffmc = 2;</code>
   * @return Whether the ffmc field is set.
   */
  boolean hasFfmc();
  /**
   * <code>.Math.Double ffmc = 2;</code>
   * @return The ffmc.
   */
  ca.hss.math.proto.Double getFfmc();
  /**
   * <code>.Math.Double ffmc = 2;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getFfmcOrBuilder();

  /**
   * <code>.Math.Double isi = 3;</code>
   * @return Whether the isi field is set.
   */
  boolean hasIsi();
  /**
   * <code>.Math.Double isi = 3;</code>
   * @return The isi.
   */
  ca.hss.math.proto.Double getIsi();
  /**
   * <code>.Math.Double isi = 3;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getIsiOrBuilder();

  /**
   * <code>.Math.Double fwi = 4;</code>
   * @return Whether the fwi field is set.
   */
  boolean hasFwi();
  /**
   * <code>.Math.Double fwi = 4;</code>
   * @return The fwi.
   */
  ca.hss.math.proto.Double getFwi();
  /**
   * <code>.Math.Double fwi = 4;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getFwiOrBuilder();

  /**
   * <code>.Math.Double dmc = 5;</code>
   * @return Whether the dmc field is set.
   */
  boolean hasDmc();
  /**
   * <code>.Math.Double dmc = 5;</code>
   * @return The dmc.
   */
  ca.hss.math.proto.Double getDmc();
  /**
   * <code>.Math.Double dmc = 5;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getDmcOrBuilder();

  /**
   * <code>.Math.Double dc = 6;</code>
   * @return Whether the dc field is set.
   */
  boolean hasDc();
  /**
   * <code>.Math.Double dc = 6;</code>
   * @return The dc.
   */
  ca.hss.math.proto.Double getDc();
  /**
   * <code>.Math.Double dc = 6;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getDcOrBuilder();

  /**
   * <code>.Math.Double bui = 7;</code>
   * @return Whether the bui field is set.
   */
  boolean hasBui();
  /**
   * <code>.Math.Double bui = 7;</code>
   * @return The bui.
   */
  ca.hss.math.proto.Double getBui();
  /**
   * <code>.Math.Double bui = 7;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getBuiOrBuilder();
}
