// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dailyConditions.proto

package ca.wise.weather.proto;

public interface DailyConditionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.DailyConditions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.WISE.WeatherProto.DailyFwi fwi = 2;</code>
   * @return Whether the fwi field is set.
   */
  boolean hasFwi();
  /**
   * <code>.WISE.WeatherProto.DailyFwi fwi = 2;</code>
   * @return The fwi.
   */
  ca.wise.weather.proto.DailyFwi getFwi();
  /**
   * <code>.WISE.WeatherProto.DailyFwi fwi = 2;</code>
   */
  ca.wise.weather.proto.DailyFwiOrBuilder getFwiOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue fromFile = 3;</code>
   * @return Whether the fromFile field is set.
   */
  boolean hasFromFile();
  /**
   * <code>.google.protobuf.BoolValue fromFile = 3;</code>
   * @return The fromFile.
   */
  com.google.protobuf.BoolValue getFromFile();
  /**
   * <code>.google.protobuf.BoolValue fromFile = 3;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getFromFileOrBuilder();

  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayWeather dayWeather = 4;</code>
   * @return Whether the dayWeather field is set.
   */
  boolean hasDayWeather();
  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayWeather dayWeather = 4;</code>
   * @return The dayWeather.
   */
  ca.wise.weather.proto.DailyConditions.DayWeather getDayWeather();
  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayWeather dayWeather = 4;</code>
   */
  ca.wise.weather.proto.DailyConditions.DayWeatherOrBuilder getDayWeatherOrBuilder();

  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayHourWeather hourWeather = 5;</code>
   * @return Whether the hourWeather field is set.
   */
  boolean hasHourWeather();
  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayHourWeather hourWeather = 5;</code>
   * @return The hourWeather.
   */
  ca.wise.weather.proto.DailyConditions.DayHourWeather getHourWeather();
  /**
   * <code>.WISE.WeatherProto.DailyConditions.DayHourWeather hourWeather = 5;</code>
   */
  ca.wise.weather.proto.DailyConditions.DayHourWeatherOrBuilder getHourWeatherOrBuilder();

  /**
   * <code>repeated .WISE.WeatherProto.DailyConditions.SpecHour specHour = 6;</code>
   */
  java.util.List<ca.wise.weather.proto.DailyConditions.SpecHour> 
      getSpecHourList();
  /**
   * <code>repeated .WISE.WeatherProto.DailyConditions.SpecHour specHour = 6;</code>
   */
  ca.wise.weather.proto.DailyConditions.SpecHour getSpecHour(int index);
  /**
   * <code>repeated .WISE.WeatherProto.DailyConditions.SpecHour specHour = 6;</code>
   */
  int getSpecHourCount();
  /**
   * <code>repeated .WISE.WeatherProto.DailyConditions.SpecHour specHour = 6;</code>
   */
  java.util.List<? extends ca.wise.weather.proto.DailyConditions.SpecHourOrBuilder> 
      getSpecHourOrBuilderList();
  /**
   * <code>repeated .WISE.WeatherProto.DailyConditions.SpecHour specHour = 6;</code>
   */
  ca.wise.weather.proto.DailyConditions.SpecHourOrBuilder getSpecHourOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.BoolValue fromEnsemble = 7;</code>
   * @return Whether the fromEnsemble field is set.
   */
  boolean hasFromEnsemble();
  /**
   * <code>.google.protobuf.BoolValue fromEnsemble = 7;</code>
   * @return The fromEnsemble.
   */
  com.google.protobuf.BoolValue getFromEnsemble();
  /**
   * <code>.google.protobuf.BoolValue fromEnsemble = 7;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getFromEnsembleOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue isModified = 8;</code>
   * @return Whether the isModified field is set.
   */
  boolean hasIsModified();
  /**
   * <code>.google.protobuf.BoolValue isModified = 8;</code>
   * @return The isModified.
   */
  com.google.protobuf.BoolValue getIsModified();
  /**
   * <code>.google.protobuf.BoolValue isModified = 8;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getIsModifiedOrBuilder();

  public ca.wise.weather.proto.DailyConditions.WeatherCase getWeatherCase();
}
