// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dailyConditions.proto

package ca.wise.weather.proto;

/**
 * Protobuf type {@code WISE.WeatherProto.DailyFwi}
 */
public final class DailyFwi extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.WeatherProto.DailyFwi)
    DailyFwiOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DailyFwi.newBuilder() to construct.
  private DailyFwi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DailyFwi() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DailyFwi();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DailyFwi(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (ffmc_ != null) {
              subBuilder = ffmc_.toBuilder();
            }
            ffmc_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ffmc_);
              ffmc_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (isi_ != null) {
              subBuilder = isi_.toBuilder();
            }
            isi_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(isi_);
              isi_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (fwi_ != null) {
              subBuilder = fwi_.toBuilder();
            }
            fwi_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fwi_);
              fwi_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (dmc_ != null) {
              subBuilder = dmc_.toBuilder();
            }
            dmc_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dmc_);
              dmc_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (dc_ != null) {
              subBuilder = dc_.toBuilder();
            }
            dc_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dc_);
              dc_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            ca.hss.math.proto.Double.Builder subBuilder = null;
            if (bui_ != null) {
              subBuilder = bui_.toBuilder();
            }
            bui_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bui_);
              bui_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.weather.proto.DailyConditionsOuterClass.internal_static_WISE_WeatherProto_DailyFwi_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.weather.proto.DailyConditionsOuterClass.internal_static_WISE_WeatherProto_DailyFwi_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.weather.proto.DailyFwi.class, ca.wise.weather.proto.DailyFwi.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int FFMC_FIELD_NUMBER = 2;
  private ca.hss.math.proto.Double ffmc_;
  /**
   * <code>.Math.Double ffmc = 2;</code>
   * @return Whether the ffmc field is set.
   */
  @java.lang.Override
  public boolean hasFfmc() {
    return ffmc_ != null;
  }
  /**
   * <code>.Math.Double ffmc = 2;</code>
   * @return The ffmc.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getFfmc() {
    return ffmc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : ffmc_;
  }
  /**
   * <code>.Math.Double ffmc = 2;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getFfmcOrBuilder() {
    return getFfmc();
  }

  public static final int ISI_FIELD_NUMBER = 3;
  private ca.hss.math.proto.Double isi_;
  /**
   * <code>.Math.Double isi = 3;</code>
   * @return Whether the isi field is set.
   */
  @java.lang.Override
  public boolean hasIsi() {
    return isi_ != null;
  }
  /**
   * <code>.Math.Double isi = 3;</code>
   * @return The isi.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getIsi() {
    return isi_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : isi_;
  }
  /**
   * <code>.Math.Double isi = 3;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getIsiOrBuilder() {
    return getIsi();
  }

  public static final int FWI_FIELD_NUMBER = 4;
  private ca.hss.math.proto.Double fwi_;
  /**
   * <code>.Math.Double fwi = 4;</code>
   * @return Whether the fwi field is set.
   */
  @java.lang.Override
  public boolean hasFwi() {
    return fwi_ != null;
  }
  /**
   * <code>.Math.Double fwi = 4;</code>
   * @return The fwi.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getFwi() {
    return fwi_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : fwi_;
  }
  /**
   * <code>.Math.Double fwi = 4;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getFwiOrBuilder() {
    return getFwi();
  }

  public static final int DMC_FIELD_NUMBER = 5;
  private ca.hss.math.proto.Double dmc_;
  /**
   * <code>.Math.Double dmc = 5;</code>
   * @return Whether the dmc field is set.
   */
  @java.lang.Override
  public boolean hasDmc() {
    return dmc_ != null;
  }
  /**
   * <code>.Math.Double dmc = 5;</code>
   * @return The dmc.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getDmc() {
    return dmc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : dmc_;
  }
  /**
   * <code>.Math.Double dmc = 5;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getDmcOrBuilder() {
    return getDmc();
  }

  public static final int DC_FIELD_NUMBER = 6;
  private ca.hss.math.proto.Double dc_;
  /**
   * <code>.Math.Double dc = 6;</code>
   * @return Whether the dc field is set.
   */
  @java.lang.Override
  public boolean hasDc() {
    return dc_ != null;
  }
  /**
   * <code>.Math.Double dc = 6;</code>
   * @return The dc.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getDc() {
    return dc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : dc_;
  }
  /**
   * <code>.Math.Double dc = 6;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getDcOrBuilder() {
    return getDc();
  }

  public static final int BUI_FIELD_NUMBER = 7;
  private ca.hss.math.proto.Double bui_;
  /**
   * <code>.Math.Double bui = 7;</code>
   * @return Whether the bui field is set.
   */
  @java.lang.Override
  public boolean hasBui() {
    return bui_ != null;
  }
  /**
   * <code>.Math.Double bui = 7;</code>
   * @return The bui.
   */
  @java.lang.Override
  public ca.hss.math.proto.Double getBui() {
    return bui_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : bui_;
  }
  /**
   * <code>.Math.Double bui = 7;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.DoubleOrBuilder getBuiOrBuilder() {
    return getBui();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (ffmc_ != null) {
      output.writeMessage(2, getFfmc());
    }
    if (isi_ != null) {
      output.writeMessage(3, getIsi());
    }
    if (fwi_ != null) {
      output.writeMessage(4, getFwi());
    }
    if (dmc_ != null) {
      output.writeMessage(5, getDmc());
    }
    if (dc_ != null) {
      output.writeMessage(6, getDc());
    }
    if (bui_ != null) {
      output.writeMessage(7, getBui());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (ffmc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFfmc());
    }
    if (isi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getIsi());
    }
    if (fwi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFwi());
    }
    if (dmc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDmc());
    }
    if (dc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDc());
    }
    if (bui_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getBui());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.weather.proto.DailyFwi)) {
      return super.equals(obj);
    }
    ca.wise.weather.proto.DailyFwi other = (ca.wise.weather.proto.DailyFwi) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasFfmc() != other.hasFfmc()) return false;
    if (hasFfmc()) {
      if (!getFfmc()
          .equals(other.getFfmc())) return false;
    }
    if (hasIsi() != other.hasIsi()) return false;
    if (hasIsi()) {
      if (!getIsi()
          .equals(other.getIsi())) return false;
    }
    if (hasFwi() != other.hasFwi()) return false;
    if (hasFwi()) {
      if (!getFwi()
          .equals(other.getFwi())) return false;
    }
    if (hasDmc() != other.hasDmc()) return false;
    if (hasDmc()) {
      if (!getDmc()
          .equals(other.getDmc())) return false;
    }
    if (hasDc() != other.hasDc()) return false;
    if (hasDc()) {
      if (!getDc()
          .equals(other.getDc())) return false;
    }
    if (hasBui() != other.hasBui()) return false;
    if (hasBui()) {
      if (!getBui()
          .equals(other.getBui())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasFfmc()) {
      hash = (37 * hash) + FFMC_FIELD_NUMBER;
      hash = (53 * hash) + getFfmc().hashCode();
    }
    if (hasIsi()) {
      hash = (37 * hash) + ISI_FIELD_NUMBER;
      hash = (53 * hash) + getIsi().hashCode();
    }
    if (hasFwi()) {
      hash = (37 * hash) + FWI_FIELD_NUMBER;
      hash = (53 * hash) + getFwi().hashCode();
    }
    if (hasDmc()) {
      hash = (37 * hash) + DMC_FIELD_NUMBER;
      hash = (53 * hash) + getDmc().hashCode();
    }
    if (hasDc()) {
      hash = (37 * hash) + DC_FIELD_NUMBER;
      hash = (53 * hash) + getDc().hashCode();
    }
    if (hasBui()) {
      hash = (37 * hash) + BUI_FIELD_NUMBER;
      hash = (53 * hash) + getBui().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.weather.proto.DailyFwi parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.DailyFwi parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.DailyFwi parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.weather.proto.DailyFwi parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.weather.proto.DailyFwi prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.WeatherProto.DailyFwi}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.WeatherProto.DailyFwi)
      ca.wise.weather.proto.DailyFwiOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.weather.proto.DailyConditionsOuterClass.internal_static_WISE_WeatherProto_DailyFwi_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.weather.proto.DailyConditionsOuterClass.internal_static_WISE_WeatherProto_DailyFwi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.weather.proto.DailyFwi.class, ca.wise.weather.proto.DailyFwi.Builder.class);
    }

    // Construct using ca.wise.weather.proto.DailyFwi.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (ffmcBuilder_ == null) {
        ffmc_ = null;
      } else {
        ffmc_ = null;
        ffmcBuilder_ = null;
      }
      if (isiBuilder_ == null) {
        isi_ = null;
      } else {
        isi_ = null;
        isiBuilder_ = null;
      }
      if (fwiBuilder_ == null) {
        fwi_ = null;
      } else {
        fwi_ = null;
        fwiBuilder_ = null;
      }
      if (dmcBuilder_ == null) {
        dmc_ = null;
      } else {
        dmc_ = null;
        dmcBuilder_ = null;
      }
      if (dcBuilder_ == null) {
        dc_ = null;
      } else {
        dc_ = null;
        dcBuilder_ = null;
      }
      if (buiBuilder_ == null) {
        bui_ = null;
      } else {
        bui_ = null;
        buiBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.weather.proto.DailyConditionsOuterClass.internal_static_WISE_WeatherProto_DailyFwi_descriptor;
    }

    @java.lang.Override
    public ca.wise.weather.proto.DailyFwi getDefaultInstanceForType() {
      return ca.wise.weather.proto.DailyFwi.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.weather.proto.DailyFwi build() {
      ca.wise.weather.proto.DailyFwi result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.weather.proto.DailyFwi buildPartial() {
      ca.wise.weather.proto.DailyFwi result = new ca.wise.weather.proto.DailyFwi(this);
      result.version_ = version_;
      if (ffmcBuilder_ == null) {
        result.ffmc_ = ffmc_;
      } else {
        result.ffmc_ = ffmcBuilder_.build();
      }
      if (isiBuilder_ == null) {
        result.isi_ = isi_;
      } else {
        result.isi_ = isiBuilder_.build();
      }
      if (fwiBuilder_ == null) {
        result.fwi_ = fwi_;
      } else {
        result.fwi_ = fwiBuilder_.build();
      }
      if (dmcBuilder_ == null) {
        result.dmc_ = dmc_;
      } else {
        result.dmc_ = dmcBuilder_.build();
      }
      if (dcBuilder_ == null) {
        result.dc_ = dc_;
      } else {
        result.dc_ = dcBuilder_.build();
      }
      if (buiBuilder_ == null) {
        result.bui_ = bui_;
      } else {
        result.bui_ = buiBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.weather.proto.DailyFwi) {
        return mergeFrom((ca.wise.weather.proto.DailyFwi)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.weather.proto.DailyFwi other) {
      if (other == ca.wise.weather.proto.DailyFwi.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasFfmc()) {
        mergeFfmc(other.getFfmc());
      }
      if (other.hasIsi()) {
        mergeIsi(other.getIsi());
      }
      if (other.hasFwi()) {
        mergeFwi(other.getFwi());
      }
      if (other.hasDmc()) {
        mergeDmc(other.getDmc());
      }
      if (other.hasDc()) {
        mergeDc(other.getDc());
      }
      if (other.hasBui()) {
        mergeBui(other.getBui());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.weather.proto.DailyFwi parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.weather.proto.DailyFwi) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private ca.hss.math.proto.Double ffmc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> ffmcBuilder_;
    /**
     * <code>.Math.Double ffmc = 2;</code>
     * @return Whether the ffmc field is set.
     */
    public boolean hasFfmc() {
      return ffmcBuilder_ != null || ffmc_ != null;
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     * @return The ffmc.
     */
    public ca.hss.math.proto.Double getFfmc() {
      if (ffmcBuilder_ == null) {
        return ffmc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : ffmc_;
      } else {
        return ffmcBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public Builder setFfmc(ca.hss.math.proto.Double value) {
      if (ffmcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ffmc_ = value;
        onChanged();
      } else {
        ffmcBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public Builder setFfmc(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (ffmcBuilder_ == null) {
        ffmc_ = builderForValue.build();
        onChanged();
      } else {
        ffmcBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public Builder mergeFfmc(ca.hss.math.proto.Double value) {
      if (ffmcBuilder_ == null) {
        if (ffmc_ != null) {
          ffmc_ =
            ca.hss.math.proto.Double.newBuilder(ffmc_).mergeFrom(value).buildPartial();
        } else {
          ffmc_ = value;
        }
        onChanged();
      } else {
        ffmcBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public Builder clearFfmc() {
      if (ffmcBuilder_ == null) {
        ffmc_ = null;
        onChanged();
      } else {
        ffmc_ = null;
        ffmcBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public ca.hss.math.proto.Double.Builder getFfmcBuilder() {
      
      onChanged();
      return getFfmcFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getFfmcOrBuilder() {
      if (ffmcBuilder_ != null) {
        return ffmcBuilder_.getMessageOrBuilder();
      } else {
        return ffmc_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : ffmc_;
      }
    }
    /**
     * <code>.Math.Double ffmc = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getFfmcFieldBuilder() {
      if (ffmcBuilder_ == null) {
        ffmcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getFfmc(),
                getParentForChildren(),
                isClean());
        ffmc_ = null;
      }
      return ffmcBuilder_;
    }

    private ca.hss.math.proto.Double isi_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> isiBuilder_;
    /**
     * <code>.Math.Double isi = 3;</code>
     * @return Whether the isi field is set.
     */
    public boolean hasIsi() {
      return isiBuilder_ != null || isi_ != null;
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     * @return The isi.
     */
    public ca.hss.math.proto.Double getIsi() {
      if (isiBuilder_ == null) {
        return isi_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : isi_;
      } else {
        return isiBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public Builder setIsi(ca.hss.math.proto.Double value) {
      if (isiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        isi_ = value;
        onChanged();
      } else {
        isiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public Builder setIsi(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (isiBuilder_ == null) {
        isi_ = builderForValue.build();
        onChanged();
      } else {
        isiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public Builder mergeIsi(ca.hss.math.proto.Double value) {
      if (isiBuilder_ == null) {
        if (isi_ != null) {
          isi_ =
            ca.hss.math.proto.Double.newBuilder(isi_).mergeFrom(value).buildPartial();
        } else {
          isi_ = value;
        }
        onChanged();
      } else {
        isiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public Builder clearIsi() {
      if (isiBuilder_ == null) {
        isi_ = null;
        onChanged();
      } else {
        isi_ = null;
        isiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public ca.hss.math.proto.Double.Builder getIsiBuilder() {
      
      onChanged();
      return getIsiFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getIsiOrBuilder() {
      if (isiBuilder_ != null) {
        return isiBuilder_.getMessageOrBuilder();
      } else {
        return isi_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : isi_;
      }
    }
    /**
     * <code>.Math.Double isi = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getIsiFieldBuilder() {
      if (isiBuilder_ == null) {
        isiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getIsi(),
                getParentForChildren(),
                isClean());
        isi_ = null;
      }
      return isiBuilder_;
    }

    private ca.hss.math.proto.Double fwi_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> fwiBuilder_;
    /**
     * <code>.Math.Double fwi = 4;</code>
     * @return Whether the fwi field is set.
     */
    public boolean hasFwi() {
      return fwiBuilder_ != null || fwi_ != null;
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     * @return The fwi.
     */
    public ca.hss.math.proto.Double getFwi() {
      if (fwiBuilder_ == null) {
        return fwi_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : fwi_;
      } else {
        return fwiBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public Builder setFwi(ca.hss.math.proto.Double value) {
      if (fwiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fwi_ = value;
        onChanged();
      } else {
        fwiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public Builder setFwi(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (fwiBuilder_ == null) {
        fwi_ = builderForValue.build();
        onChanged();
      } else {
        fwiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public Builder mergeFwi(ca.hss.math.proto.Double value) {
      if (fwiBuilder_ == null) {
        if (fwi_ != null) {
          fwi_ =
            ca.hss.math.proto.Double.newBuilder(fwi_).mergeFrom(value).buildPartial();
        } else {
          fwi_ = value;
        }
        onChanged();
      } else {
        fwiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public Builder clearFwi() {
      if (fwiBuilder_ == null) {
        fwi_ = null;
        onChanged();
      } else {
        fwi_ = null;
        fwiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public ca.hss.math.proto.Double.Builder getFwiBuilder() {
      
      onChanged();
      return getFwiFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getFwiOrBuilder() {
      if (fwiBuilder_ != null) {
        return fwiBuilder_.getMessageOrBuilder();
      } else {
        return fwi_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : fwi_;
      }
    }
    /**
     * <code>.Math.Double fwi = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getFwiFieldBuilder() {
      if (fwiBuilder_ == null) {
        fwiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getFwi(),
                getParentForChildren(),
                isClean());
        fwi_ = null;
      }
      return fwiBuilder_;
    }

    private ca.hss.math.proto.Double dmc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> dmcBuilder_;
    /**
     * <code>.Math.Double dmc = 5;</code>
     * @return Whether the dmc field is set.
     */
    public boolean hasDmc() {
      return dmcBuilder_ != null || dmc_ != null;
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     * @return The dmc.
     */
    public ca.hss.math.proto.Double getDmc() {
      if (dmcBuilder_ == null) {
        return dmc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : dmc_;
      } else {
        return dmcBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public Builder setDmc(ca.hss.math.proto.Double value) {
      if (dmcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dmc_ = value;
        onChanged();
      } else {
        dmcBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public Builder setDmc(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (dmcBuilder_ == null) {
        dmc_ = builderForValue.build();
        onChanged();
      } else {
        dmcBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public Builder mergeDmc(ca.hss.math.proto.Double value) {
      if (dmcBuilder_ == null) {
        if (dmc_ != null) {
          dmc_ =
            ca.hss.math.proto.Double.newBuilder(dmc_).mergeFrom(value).buildPartial();
        } else {
          dmc_ = value;
        }
        onChanged();
      } else {
        dmcBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public Builder clearDmc() {
      if (dmcBuilder_ == null) {
        dmc_ = null;
        onChanged();
      } else {
        dmc_ = null;
        dmcBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public ca.hss.math.proto.Double.Builder getDmcBuilder() {
      
      onChanged();
      return getDmcFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getDmcOrBuilder() {
      if (dmcBuilder_ != null) {
        return dmcBuilder_.getMessageOrBuilder();
      } else {
        return dmc_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : dmc_;
      }
    }
    /**
     * <code>.Math.Double dmc = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getDmcFieldBuilder() {
      if (dmcBuilder_ == null) {
        dmcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getDmc(),
                getParentForChildren(),
                isClean());
        dmc_ = null;
      }
      return dmcBuilder_;
    }

    private ca.hss.math.proto.Double dc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> dcBuilder_;
    /**
     * <code>.Math.Double dc = 6;</code>
     * @return Whether the dc field is set.
     */
    public boolean hasDc() {
      return dcBuilder_ != null || dc_ != null;
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     * @return The dc.
     */
    public ca.hss.math.proto.Double getDc() {
      if (dcBuilder_ == null) {
        return dc_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : dc_;
      } else {
        return dcBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public Builder setDc(ca.hss.math.proto.Double value) {
      if (dcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dc_ = value;
        onChanged();
      } else {
        dcBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public Builder setDc(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (dcBuilder_ == null) {
        dc_ = builderForValue.build();
        onChanged();
      } else {
        dcBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public Builder mergeDc(ca.hss.math.proto.Double value) {
      if (dcBuilder_ == null) {
        if (dc_ != null) {
          dc_ =
            ca.hss.math.proto.Double.newBuilder(dc_).mergeFrom(value).buildPartial();
        } else {
          dc_ = value;
        }
        onChanged();
      } else {
        dcBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public Builder clearDc() {
      if (dcBuilder_ == null) {
        dc_ = null;
        onChanged();
      } else {
        dc_ = null;
        dcBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public ca.hss.math.proto.Double.Builder getDcBuilder() {
      
      onChanged();
      return getDcFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getDcOrBuilder() {
      if (dcBuilder_ != null) {
        return dcBuilder_.getMessageOrBuilder();
      } else {
        return dc_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : dc_;
      }
    }
    /**
     * <code>.Math.Double dc = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getDcFieldBuilder() {
      if (dcBuilder_ == null) {
        dcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getDc(),
                getParentForChildren(),
                isClean());
        dc_ = null;
      }
      return dcBuilder_;
    }

    private ca.hss.math.proto.Double bui_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> buiBuilder_;
    /**
     * <code>.Math.Double bui = 7;</code>
     * @return Whether the bui field is set.
     */
    public boolean hasBui() {
      return buiBuilder_ != null || bui_ != null;
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     * @return The bui.
     */
    public ca.hss.math.proto.Double getBui() {
      if (buiBuilder_ == null) {
        return bui_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : bui_;
      } else {
        return buiBuilder_.getMessage();
      }
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public Builder setBui(ca.hss.math.proto.Double value) {
      if (buiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bui_ = value;
        onChanged();
      } else {
        buiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public Builder setBui(
        ca.hss.math.proto.Double.Builder builderForValue) {
      if (buiBuilder_ == null) {
        bui_ = builderForValue.build();
        onChanged();
      } else {
        buiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public Builder mergeBui(ca.hss.math.proto.Double value) {
      if (buiBuilder_ == null) {
        if (bui_ != null) {
          bui_ =
            ca.hss.math.proto.Double.newBuilder(bui_).mergeFrom(value).buildPartial();
        } else {
          bui_ = value;
        }
        onChanged();
      } else {
        buiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public Builder clearBui() {
      if (buiBuilder_ == null) {
        bui_ = null;
        onChanged();
      } else {
        bui_ = null;
        buiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public ca.hss.math.proto.Double.Builder getBuiBuilder() {
      
      onChanged();
      return getBuiFieldBuilder().getBuilder();
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    public ca.hss.math.proto.DoubleOrBuilder getBuiOrBuilder() {
      if (buiBuilder_ != null) {
        return buiBuilder_.getMessageOrBuilder();
      } else {
        return bui_ == null ?
            ca.hss.math.proto.Double.getDefaultInstance() : bui_;
      }
    }
    /**
     * <code>.Math.Double bui = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
        getBuiFieldBuilder() {
      if (buiBuilder_ == null) {
        buiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                getBui(),
                getParentForChildren(),
                isClean());
        bui_ = null;
      }
      return buiBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.WeatherProto.DailyFwi)
  }

  // @@protoc_insertion_point(class_scope:WISE.WeatherProto.DailyFwi)
  private static final ca.wise.weather.proto.DailyFwi DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.weather.proto.DailyFwi();
  }

  public static ca.wise.weather.proto.DailyFwi getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DailyFwi>
      PARSER = new com.google.protobuf.AbstractParser<DailyFwi>() {
    @java.lang.Override
    public DailyFwi parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DailyFwi(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DailyFwi> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DailyFwi> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.weather.proto.DailyFwi getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

