// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStream.proto

package ca.wise.weather.proto;

public final class WeatherStreamOuterClass {
  private WeatherStreamOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WeatherStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WeatherStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WeatherStream_ConditionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WeatherStream_ConditionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WeatherStream_ABC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WeatherStream_ABC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WeatherStream_StartingCodes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WeatherStream_StartingCodes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023weatherStream.proto\022\021WISE.WeatherProto" +
      "\032\nmath.proto\032\013wtime.proto\032\025dailyConditio" +
      "ns.proto\032\036google/protobuf/wrappers.proto" +
      "\"\337\010\n\rWeatherStream\022\017\n\007version\030\001 \001(\005\022\034\n\024d" +
      "ataImportedFromFile\030\002 \001(\010\022.\n\tstartHour\030\003" +
      " \001(\0132\033.google.protobuf.Int32Value\022,\n\007end" +
      "Hour\030\004 \001(\0132\033.google.protobuf.Int32Value\022" +
      "I\n\017dailyConditions\030\005 \001(\0132..WISE.WeatherP" +
      "roto.WeatherStream.ConditionListH\000\022\022\n\010fi" +
      "lename\030\006 \001(\tH\000\0225\n\021hffmcUseSpecified\030\007 \001(" +
      "\0132\032.google.protobuf.BoolValue\022#\n\tstartTi" +
      "me\030\010 \001(\0132\020.HSS.Times.WTime\022\'\n\thffmcTime\030" +
      "\t \001(\0132\024.HSS.Times.WTimeSpan\022\033\n\005hffmc\030\n \001" +
      "(\0132\014.Math.Double\022@\n\013hffmcMethod\030\013 \001(\0162+." +
      "WISE.WeatherProto.WeatherStream.FFMCMeth" +
      "od\0229\n\013temperature\030\014 \001(\0132$.WISE.WeatherPr" +
      "oto.WeatherStream.ABC\0222\n\004wind\030\r \001(\0132$.WI" +
      "SE.WeatherProto.WeatherStream.ABC\022E\n\rsta" +
      "rtingCodes\030\016 \001(\0132..WISE.WeatherProto.Wea" +
      "therStream.StartingCodes\022<\n\030dataImported" +
      "FromEnsemble\030\017 \001(\0132\032.google.protobuf.Boo" +
      "lValue\032L\n\rConditionList\022;\n\017dailyConditio" +
      "ns\030\001 \003(\0132\".WISE.WeatherProto.DailyCondit" +
      "ions\032[\n\003ABC\022\033\n\005alpha\030\001 \001(\0132\014.Math.Double" +
      "\022\032\n\004beta\030\002 \001(\0132\014.Math.Double\022\033\n\005gamma\030\003 " +
      "\001(\0132\014.Math.Double\032\240\001\n\rStartingCodes\022\032\n\004f" +
      "fmc\030\001 \001(\0132\014.Math.Double\022\031\n\003dmc\030\002 \001(\0132\014.M" +
      "ath.Double\022\030\n\002dc\030\003 \001(\0132\014.Math.Double\022\031\n\003" +
      "bui\030\004 \001(\0132\014.Math.Double\022#\n\rprecipitation" +
      "\030\005 \001(\0132\014.Math.Double\"4\n\nFFMCMethod\022\016\n\nVA" +
      "N_WAGNER\020\000\022\n\n\006HYBRID\020\001\022\n\n\006LAWSON\020\002B\006\n\004da" +
      "taB-\n\025ca.wise.weather.protoP\001\252\002\021WISE.Wea" +
      "therProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.hss.times.proto.WTimePackage.getDescriptor(),
          ca.wise.weather.proto.DailyConditionsOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_WeatherProto_WeatherStream_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_WeatherProto_WeatherStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WeatherStream_descriptor,
        new java.lang.String[] { "Version", "DataImportedFromFile", "StartHour", "EndHour", "DailyConditions", "Filename", "HffmcUseSpecified", "StartTime", "HffmcTime", "Hffmc", "HffmcMethod", "Temperature", "Wind", "StartingCodes", "DataImportedFromEnsemble", "Data", });
    internal_static_WISE_WeatherProto_WeatherStream_ConditionList_descriptor =
      internal_static_WISE_WeatherProto_WeatherStream_descriptor.getNestedTypes().get(0);
    internal_static_WISE_WeatherProto_WeatherStream_ConditionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WeatherStream_ConditionList_descriptor,
        new java.lang.String[] { "DailyConditions", });
    internal_static_WISE_WeatherProto_WeatherStream_ABC_descriptor =
      internal_static_WISE_WeatherProto_WeatherStream_descriptor.getNestedTypes().get(1);
    internal_static_WISE_WeatherProto_WeatherStream_ABC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WeatherStream_ABC_descriptor,
        new java.lang.String[] { "Alpha", "Beta", "Gamma", });
    internal_static_WISE_WeatherProto_WeatherStream_StartingCodes_descriptor =
      internal_static_WISE_WeatherProto_WeatherStream_descriptor.getNestedTypes().get(2);
    internal_static_WISE_WeatherProto_WeatherStream_StartingCodes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WeatherStream_StartingCodes_descriptor,
        new java.lang.String[] { "Ffmc", "Dmc", "Dc", "Bui", "Precipitation", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.hss.times.proto.WTimePackage.getDescriptor();
    ca.wise.weather.proto.DailyConditionsOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
