// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherGridFilter.proto

package ca.wise.weather.proto;

public interface WeatherGridFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.WeatherGridFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   * @return The startTime.
   */
  ca.hss.times.proto.WTime getStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 2;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   * @return The endTime.
   */
  ca.hss.times.proto.WTime getEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 3;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getEndTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan startTimeOfDay = 4;</code>
   * @return Whether the startTimeOfDay field is set.
   */
  boolean hasStartTimeOfDay();
  /**
   * <code>.HSS.Times.WTimeSpan startTimeOfDay = 4;</code>
   * @return The startTimeOfDay.
   */
  ca.hss.times.proto.WTimeSpan getStartTimeOfDay();
  /**
   * <code>.HSS.Times.WTimeSpan startTimeOfDay = 4;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getStartTimeOfDayOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan endTimeOfDay = 5;</code>
   * @return Whether the endTimeOfDay field is set.
   */
  boolean hasEndTimeOfDay();
  /**
   * <code>.HSS.Times.WTimeSpan endTimeOfDay = 5;</code>
   * @return The endTimeOfDay.
   */
  ca.hss.times.proto.WTimeSpan getEndTimeOfDay();
  /**
   * <code>.HSS.Times.WTimeSpan endTimeOfDay = 5;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getEndTimeOfDayOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne temperature = 6;</code>
   * @return Whether the temperature field is set.
   */
  boolean hasTemperature();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne temperature = 6;</code>
   * @return The temperature.
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOne getTemperature();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne temperature = 6;</code>
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOneOrBuilder getTemperatureOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne rh = 7;</code>
   * @return Whether the rh field is set.
   */
  boolean hasRh();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne rh = 7;</code>
   * @return The rh.
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOne getRh();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne rh = 7;</code>
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOneOrBuilder getRhOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne precipitation = 8;</code>
   * @return Whether the precipitation field is set.
   */
  boolean hasPrecipitation();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne precipitation = 8;</code>
   * @return The precipitation.
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOne getPrecipitation();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne precipitation = 8;</code>
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOneOrBuilder getPrecipitationOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne windSpeed = 9;</code>
   * @return Whether the windSpeed field is set.
   */
  boolean hasWindSpeed();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne windSpeed = 9;</code>
   * @return The windSpeed.
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOne getWindSpeed();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeOne windSpeed = 9;</code>
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeOneOrBuilder getWindSpeedOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeTwo windDirection = 10;</code>
   * @return Whether the windDirection field is set.
   */
  boolean hasWindDirection();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeTwo windDirection = 10;</code>
   * @return The windDirection.
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeTwo getWindDirection();
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter.GridTypeTwo windDirection = 10;</code>
   */
  ca.wise.weather.proto.WeatherGridFilter.GridTypeTwoOrBuilder getWindDirectionOrBuilder();

  /**
   * <code>.Geography.GeoPoly polygons = 11;</code>
   * @return Whether the polygons field is set.
   */
  boolean hasPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 11;</code>
   * @return The polygons.
   */
  ca.hss.math.proto.GeoPoly getPolygons();
  /**
   * <code>.Geography.GeoPoly polygons = 11;</code>
   */
  ca.hss.math.proto.GeoPolyOrBuilder getPolygonsOrBuilder();

  /**
   * <code>string filename = 12;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 12;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>bool landscape = 13;</code>
   * @return The landscape.
   */
  boolean getLandscape();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 14;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 14;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 14;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 15;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 15;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 15;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <pre>
   * types are consistent with the Project versions, but no longer consistent with what's in the Fire object - resolve for consistency
   * </pre>
   *
   * <code>uint32 color = 16;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <pre>
   * types are consistent with the Project versions, but no longer consistent with what's in the Fire object - resolve for consistency
   * </pre>
   *
   * <code>uint32 color = 16;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint64 size = 17;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>uint64 size = 17;</code>
   * @return The size.
   */
  long getSize();

  public ca.wise.weather.proto.WeatherGridFilter.ShapeCase getShapeCase();
}
