// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStream.proto

package ca.wise.weather.proto;

public interface WeatherStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.WeatherStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>bool dataImportedFromFile = 2;</code>
   * @return The dataImportedFromFile.
   */
  boolean getDataImportedFromFile();

  /**
   * <code>.google.protobuf.Int32Value startHour = 3;</code>
   * @return Whether the startHour field is set.
   */
  boolean hasStartHour();
  /**
   * <code>.google.protobuf.Int32Value startHour = 3;</code>
   * @return The startHour.
   */
  com.google.protobuf.Int32Value getStartHour();
  /**
   * <code>.google.protobuf.Int32Value startHour = 3;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getStartHourOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value endHour = 4;</code>
   * @return Whether the endHour field is set.
   */
  boolean hasEndHour();
  /**
   * <code>.google.protobuf.Int32Value endHour = 4;</code>
   * @return The endHour.
   */
  com.google.protobuf.Int32Value getEndHour();
  /**
   * <code>.google.protobuf.Int32Value endHour = 4;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getEndHourOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherStream.ConditionList dailyConditions = 5;</code>
   * @return Whether the dailyConditions field is set.
   */
  boolean hasDailyConditions();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ConditionList dailyConditions = 5;</code>
   * @return The dailyConditions.
   */
  ca.wise.weather.proto.WeatherStream.ConditionList getDailyConditions();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ConditionList dailyConditions = 5;</code>
   */
  ca.wise.weather.proto.WeatherStream.ConditionListOrBuilder getDailyConditionsOrBuilder();

  /**
   * <code>string filename = 6;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 6;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>.google.protobuf.BoolValue hffmcUseSpecified = 7;</code>
   * @return Whether the hffmcUseSpecified field is set.
   */
  boolean hasHffmcUseSpecified();
  /**
   * <code>.google.protobuf.BoolValue hffmcUseSpecified = 7;</code>
   * @return The hffmcUseSpecified.
   */
  com.google.protobuf.BoolValue getHffmcUseSpecified();
  /**
   * <code>.google.protobuf.BoolValue hffmcUseSpecified = 7;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getHffmcUseSpecifiedOrBuilder();

  /**
   * <code>.HSS.Times.WTime startTime = 8;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 8;</code>
   * @return The startTime.
   */
  ca.hss.times.proto.WTime getStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 8;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan hffmcTime = 9;</code>
   * @return Whether the hffmcTime field is set.
   */
  boolean hasHffmcTime();
  /**
   * <code>.HSS.Times.WTimeSpan hffmcTime = 9;</code>
   * @return The hffmcTime.
   */
  ca.hss.times.proto.WTimeSpan getHffmcTime();
  /**
   * <code>.HSS.Times.WTimeSpan hffmcTime = 9;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getHffmcTimeOrBuilder();

  /**
   * <code>.Math.Double hffmc = 10;</code>
   * @return Whether the hffmc field is set.
   */
  boolean hasHffmc();
  /**
   * <code>.Math.Double hffmc = 10;</code>
   * @return The hffmc.
   */
  ca.hss.math.proto.Double getHffmc();
  /**
   * <code>.Math.Double hffmc = 10;</code>
   */
  ca.hss.math.proto.DoubleOrBuilder getHffmcOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherStream.FFMCMethod hffmcMethod = 11;</code>
   * @return The enum numeric value on the wire for hffmcMethod.
   */
  int getHffmcMethodValue();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.FFMCMethod hffmcMethod = 11;</code>
   * @return The hffmcMethod.
   */
  ca.wise.weather.proto.WeatherStream.FFMCMethod getHffmcMethod();

  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC temperature = 12;</code>
   * @return Whether the temperature field is set.
   */
  boolean hasTemperature();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC temperature = 12;</code>
   * @return The temperature.
   */
  ca.wise.weather.proto.WeatherStream.ABC getTemperature();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC temperature = 12;</code>
   */
  ca.wise.weather.proto.WeatherStream.ABCOrBuilder getTemperatureOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC wind = 13;</code>
   * @return Whether the wind field is set.
   */
  boolean hasWind();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC wind = 13;</code>
   * @return The wind.
   */
  ca.wise.weather.proto.WeatherStream.ABC getWind();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.ABC wind = 13;</code>
   */
  ca.wise.weather.proto.WeatherStream.ABCOrBuilder getWindOrBuilder();

  /**
   * <code>.WISE.WeatherProto.WeatherStream.StartingCodes startingCodes = 14;</code>
   * @return Whether the startingCodes field is set.
   */
  boolean hasStartingCodes();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.StartingCodes startingCodes = 14;</code>
   * @return The startingCodes.
   */
  ca.wise.weather.proto.WeatherStream.StartingCodes getStartingCodes();
  /**
   * <code>.WISE.WeatherProto.WeatherStream.StartingCodes startingCodes = 14;</code>
   */
  ca.wise.weather.proto.WeatherStream.StartingCodesOrBuilder getStartingCodesOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue dataImportedFromEnsemble = 15;</code>
   * @return Whether the dataImportedFromEnsemble field is set.
   */
  boolean hasDataImportedFromEnsemble();
  /**
   * <code>.google.protobuf.BoolValue dataImportedFromEnsemble = 15;</code>
   * @return The dataImportedFromEnsemble.
   */
  com.google.protobuf.BoolValue getDataImportedFromEnsemble();
  /**
   * <code>.google.protobuf.BoolValue dataImportedFromEnsemble = 15;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getDataImportedFromEnsembleOrBuilder();

  public ca.wise.weather.proto.WeatherStream.DataCase getDataCase();
}
