// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: windGrid.proto

package ca.wise.weather.proto;

public final class WindGridOuterClass {
  private WindGridOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WindGrid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WindGrid_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WindGrid_SectorData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WindGrid_SectorData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WindGrid_SectorData_GridData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WindGrid_SectorData_GridData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_SpecificDirection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_SpecificDirection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016windGrid.proto\022\021WISE.WeatherProto\032\rwcs" +
      "Data.proto\032\nmath.proto\032\013wtime.proto\"\352\t\n\010" +
      "WindGrid\022\017\n\007version\030\001 \001(\005\0222\n\004type\030\002 \001(\0162" +
      "$.WISE.WeatherProto.WindGrid.GridType\0222\n" +
      "\021defaultSectorData\030\003 \001(\0132\027.WISE.GridProt" +
      "o.wcsData\022:\n\nsectorData\030\004 \003(\0132&.WISE.Wea" +
      "therProto.WindGrid.SectorData\022#\n\tstartTi" +
      "me\030\005 \001(\0132\020.HSS.Times.WTime\022!\n\007endTime\030\006 " +
      "\001(\0132\020.HSS.Times.WTime\022\'\n\tstartSpan\030\007 \001(\013" +
      "2\024.HSS.Times.WTimeSpan\022%\n\007endSpan\030\010 \001(\0132" +
      "\024.HSS.Times.WTimeSpan\022\033\n\021applyFileDefaul" +
      "ts\030\t \001(\010H\000\022\032\n\020applyFileSectors\030\n \001(\010H\000\022\021" +
      "\n\004name\030\013 \001(\tH\001\210\001\001\022\025\n\010comments\030\014 \001(\tH\002\210\001\001" +
      "\032\334\005\n\nSectorData\022\017\n\007version\030\001 \001(\005\022\r\n\005labe" +
      "l\030\002 \001(\t\022J\n\tdirection\030\003 \001(\01327.WISE.Weathe" +
      "rProto.WindGrid.SectorData.DirectionWrap" +
      "per\022F\n\rsectorEntries\030\004 \003(\0132/.WISE.Weathe" +
      "rProto.WindGrid.SectorData.GridData\032_\n\010G" +
      "ridData\022\017\n\007version\030\001 \001(\005\022\033\n\005speed\030\002 \001(\0132" +
      "\014.Math.Double\022%\n\004data\030\003 \001(\0132\027.WISE.GridP" +
      "roto.wcsData\032\270\003\n\020DirectionWrapper\022b\n\021car" +
      "dinalDirection\030\001 \001(\0162E.WISE.WeatherProto" +
      ".WindGrid.SectorData.DirectionWrapper.Wi" +
      "ndDirectionH\000\022g\n\022specifiedDirection\030\002 \001(" +
      "\0132I.WISE.WeatherProto.WindGrid.SectorDat" +
      "a.DirectionWrapper.SpecificDirectionH\000\032S" +
      "\n\021SpecificDirection\022\036\n\010minAngle\030\001 \001(\0132\014." +
      "Math.Double\022\036\n\010maxAngle\030\002 \001(\0132\014.Math.Dou" +
      "ble\"u\n\rWindDirection\022\010\n\004East\020\000\022\t\n\005North\020" +
      "\001\022\r\n\tNortheast\020\002\022\r\n\tNorthwest\020\003\022\t\n\005South" +
      "\020\004\022\r\n\tSoutheast\020\005\022\r\n\tSouthwest\020\006\022\010\n\004West" +
      "\020\007B\013\n\tdirection\",\n\010GridType\022\r\n\tWindSpeed" +
      "\020\000\022\021\n\rWindDirection\020\001B\013\n\tApplyFileB\007\n\005_n" +
      "ameB\013\n\t_commentsB-\n\025ca.wise.weather.prot" +
      "oP\001\252\002\021WISE.WeatherProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.wise.grid.proto.wcsDataPackage.getDescriptor(),
          ca.hss.math.proto.Math.getDescriptor(),
          ca.hss.times.proto.WTimePackage.getDescriptor(),
        });
    internal_static_WISE_WeatherProto_WindGrid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_WeatherProto_WindGrid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WindGrid_descriptor,
        new java.lang.String[] { "Version", "Type", "DefaultSectorData", "SectorData", "StartTime", "EndTime", "StartSpan", "EndSpan", "ApplyFileDefaults", "ApplyFileSectors", "Name", "Comments", "ApplyFile", "Name", "Comments", });
    internal_static_WISE_WeatherProto_WindGrid_SectorData_descriptor =
      internal_static_WISE_WeatherProto_WindGrid_descriptor.getNestedTypes().get(0);
    internal_static_WISE_WeatherProto_WindGrid_SectorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WindGrid_SectorData_descriptor,
        new java.lang.String[] { "Version", "Label", "Direction", "SectorEntries", });
    internal_static_WISE_WeatherProto_WindGrid_SectorData_GridData_descriptor =
      internal_static_WISE_WeatherProto_WindGrid_SectorData_descriptor.getNestedTypes().get(0);
    internal_static_WISE_WeatherProto_WindGrid_SectorData_GridData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WindGrid_SectorData_GridData_descriptor,
        new java.lang.String[] { "Version", "Speed", "Data", });
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_descriptor =
      internal_static_WISE_WeatherProto_WindGrid_SectorData_descriptor.getNestedTypes().get(1);
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_descriptor,
        new java.lang.String[] { "CardinalDirection", "SpecifiedDirection", "Direction", });
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_SpecificDirection_descriptor =
      internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_descriptor.getNestedTypes().get(0);
    internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_SpecificDirection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_WeatherProto_WindGrid_SectorData_DirectionWrapper_SpecificDirection_descriptor,
        new java.lang.String[] { "MinAngle", "MaxAngle", });
    ca.wise.grid.proto.wcsDataPackage.getDescriptor();
    ca.hss.math.proto.Math.getDescriptor();
    ca.hss.times.proto.WTimePackage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
