// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: windGrid.proto

package ca.wise.weather.proto;

public interface WindGridOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.WeatherProto.WindGrid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.WISE.WeatherProto.WindGrid.GridType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.WISE.WeatherProto.WindGrid.GridType type = 2;</code>
   * @return The type.
   */
  ca.wise.weather.proto.WindGrid.GridType getType();

  /**
   * <code>.WISE.GridProto.wcsData defaultSectorData = 3;</code>
   * @return Whether the defaultSectorData field is set.
   */
  boolean hasDefaultSectorData();
  /**
   * <code>.WISE.GridProto.wcsData defaultSectorData = 3;</code>
   * @return The defaultSectorData.
   */
  ca.wise.grid.proto.wcsData getDefaultSectorData();
  /**
   * <code>.WISE.GridProto.wcsData defaultSectorData = 3;</code>
   */
  ca.wise.grid.proto.wcsDataOrBuilder getDefaultSectorDataOrBuilder();

  /**
   * <code>repeated .WISE.WeatherProto.WindGrid.SectorData sectorData = 4;</code>
   */
  java.util.List<ca.wise.weather.proto.WindGrid.SectorData> 
      getSectorDataList();
  /**
   * <code>repeated .WISE.WeatherProto.WindGrid.SectorData sectorData = 4;</code>
   */
  ca.wise.weather.proto.WindGrid.SectorData getSectorData(int index);
  /**
   * <code>repeated .WISE.WeatherProto.WindGrid.SectorData sectorData = 4;</code>
   */
  int getSectorDataCount();
  /**
   * <code>repeated .WISE.WeatherProto.WindGrid.SectorData sectorData = 4;</code>
   */
  java.util.List<? extends ca.wise.weather.proto.WindGrid.SectorDataOrBuilder> 
      getSectorDataOrBuilderList();
  /**
   * <code>repeated .WISE.WeatherProto.WindGrid.SectorData sectorData = 4;</code>
   */
  ca.wise.weather.proto.WindGrid.SectorDataOrBuilder getSectorDataOrBuilder(
      int index);

  /**
   * <code>.HSS.Times.WTime startTime = 5;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 5;</code>
   * @return The startTime.
   */
  ca.hss.times.proto.WTime getStartTime();
  /**
   * <code>.HSS.Times.WTime startTime = 5;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTime endTime = 6;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 6;</code>
   * @return The endTime.
   */
  ca.hss.times.proto.WTime getEndTime();
  /**
   * <code>.HSS.Times.WTime endTime = 6;</code>
   */
  ca.hss.times.proto.WTimeOrBuilder getEndTimeOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan startSpan = 7;</code>
   * @return Whether the startSpan field is set.
   */
  boolean hasStartSpan();
  /**
   * <code>.HSS.Times.WTimeSpan startSpan = 7;</code>
   * @return The startSpan.
   */
  ca.hss.times.proto.WTimeSpan getStartSpan();
  /**
   * <code>.HSS.Times.WTimeSpan startSpan = 7;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getStartSpanOrBuilder();

  /**
   * <code>.HSS.Times.WTimeSpan endSpan = 8;</code>
   * @return Whether the endSpan field is set.
   */
  boolean hasEndSpan();
  /**
   * <code>.HSS.Times.WTimeSpan endSpan = 8;</code>
   * @return The endSpan.
   */
  ca.hss.times.proto.WTimeSpan getEndSpan();
  /**
   * <code>.HSS.Times.WTimeSpan endSpan = 8;</code>
   */
  ca.hss.times.proto.WTimeSpanOrBuilder getEndSpanOrBuilder();

  /**
   * <code>bool applyFileDefaults = 9;</code>
   * @return The applyFileDefaults.
   */
  boolean getApplyFileDefaults();

  /**
   * <code>bool applyFileSectors = 10;</code>
   * @return The applyFileSectors.
   */
  boolean getApplyFileSectors();

  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 11;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 11;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * not really optional but need to be able to suppress it in the old file format
   * </pre>
   *
   * <code>string name = 11;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 12;</code>
   * @return Whether the comments field is set.
   */
  boolean hasComments();
  /**
   * <code>string comments = 12;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 12;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  public ca.wise.weather.proto.WindGrid.ApplyFileCase getApplyFileCase();
}
